title: "TeraBox Player Guide"
description: "Learn how to use the TeraBox Link to Video Player – Free Online Streaming Tool."
baseurl: "" # leave empty unless in subfolder
url: "https://rfbots.github.io/teraboxopbot"
theme: minima
plugins:
  - jekyll-seo-tag
# Custom CSS
minima:
  skin: classic
  custom_css:
    - /assets/css/style.scss
